export const enum MessageType {
  Ping = 0,
  Subscribe = -1,
  Client = 1,
  Screen,
  Directory,
  Process = 8,
  Mouse,
  MouseMove,
  Key,
  Transfers = 9,
  DownloadToServer = 10,
  TransferAction = 11,
  UploadToClient = 12,
}
