/**
 * Redux action constants
 */
export enum Action {
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',

  CLIENTS_LIST_INIT = 'CLIENTS_LIST_INIT',
  CLIENTS_RESET = 'CLIENTS_RESET',
  CLIENT_CONNECT = 'CLIENT_CONNECT',
  CLIENT_DISCONNECT = 'CLIENT_DISCONNECT',
  CLIENT_UPDATE = 'CLIENT_UPDATE',
  SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT',

  SET_FILE_LIST = 'SET_FILE_LIST',
  SET_CURRENT_DIRECTORY = 'SET_CURRENT_DIRECTORY',

  PROCESS_SET_LIST = 'PROCESS_SET_LIST',

  SCREEN_SET_FRAME = 'SCREEN_SET_FRAME',
  SCREEN_RESET_FPS = 'SCREEN_RESET_FPS',

  TRANSFER_LIST = 'TRANSFER_LIST',
}
